import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'

import {
  ClerkProvider,
} from '@clerk/nextjs'

import Navber from "./Navbar/page";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: 'BlogAI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
      <html lang="en" data-theme="light">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Head>
          </Head>
          <Navber></Navber>
          <main>
            {children}
          </main>

        </body>
      </html>
    </ClerkProvider>
  );
}
